Version 1.6.0
conda-forge/ecmwf-api-client-feedstock pull request #8
Opened 2020-10-30 16:45 UTC by StephanSiemen

For Python 3.9.0

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2020-10-30 16:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * noarch: python recipes are recommended to have a lower bound on minimum python bound. This recommendation will become requirement in a future version.

2020-10-30 16:46 UTC, StephanSiemen commented
@conda-forge-admin, please rerender

2020-10-30 19:43 UTC, StephanSiemen commented
Delete this because there is now an automatically generated PR https://github.com/conda-forge/ecmwf-api-client-feedstock/pull/9

2020-10-30 19:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2020-10-31 06:30 UTC, avalentino requested changes

2020-10-31 06:30 UTC, avalentino commented on recipe/meta.yaml
> +  noarch: python >3.5
Specifying the minimum version here seems to cause problems.
IMHO having "python >3.5" in the requirements/host section is enough to build properly.

2020-10-31 06:30 UTC, avalentino commented on recipe/meta.yaml
>      - python
Probably the constraint on the python version should be put also in this point

2021-01-10 16:33 UTC, avalentino commented
Closing. V1.6.1 is already in now.

2021-01-10 16:33 UTC, closed without merging